/*
 * rb_devices.h - desktop device catalogue for Room Browser core.
 *
 * The counterpart of the Android edition's Devices.kt: a profile presents
 * itself as a real machine rather than as a bare User-Agent string. The
 * Android catalogue is 1,021 handsets drawn from Google's public list; there
 * is no equivalent list for desktops and far fewer models matter, so this
 * one is curated - real, shipping machines with the OS each one actually
 * runs, the GPU it actually ships, and a Chrome release from its year.
 *
 * The split between the two implementation files is deliberate:
 *
 *   rb_devices.c  the catalogue. GENERATED by scripts/gen-devices.py; do
 *                 not edit by hand. The table itself, plus the three
 *                 lookups that are pure data access.
 *   rb_device.c   behaviour: choosing a device, resolving a profile's
 *                 User-Agent from it, and building the document-start
 *                 script. Hand-written, because it is logic, not data.
 *
 * What a device decides is documented in SECURITY.md, and it is the same
 * bargain the Android edition makes: the non-geometric surface a machine
 * determines (UA, client hints, platform, memory, cores, WebGL strings) is
 * presented; screen geometry and real capabilities are not, because the page
 * really is laid out on this screen and a claim that contradicted the
 * viewport would render it wrongly and be the cheapest spoofing signal
 * there is.
 */

#ifndef RB_DEVICES_H
#define RB_DEVICES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *id;               /* stable id, e.g. "dell-xps-15-9530-windows" */
    const char *brand;            /* "Dell" */
    const char *model;            /* "XPS 15 9530" */
    int         year;             /* release year, 2022-2025 */
    const char *os;               /* "windows" | "macos" | "linux" */
    const char *form;             /* "laptop" | "desktop" */
    const char *arch;             /* "x86" | "arm" - userAgentData architecture */
    const char *chrome;           /* full Chrome version, e.g. "131.0.6778.135" */
    const char *gpu_vendor;       /* WebGL UNMASKED_VENDOR_WEBGL */
    const char *gpu_renderer;     /* WebGL UNMASKED_RENDERER_WEBGL */
    int         cores;            /* hardwareConcurrency */
    int         memory;           /* navigator.deviceMemory - never above 8,
                                     which is where Chromium caps it, so a
                                     64 GB workstation honestly reports 8 */
    const char *platform;         /* navigator.platform: Win32 / MacIntel /
                                     Linux x86_64 */
    const char *ua_platform;      /* userAgentData.platform: Windows / macOS /
                                     Linux */
    const char *platform_version; /* userAgentData platformVersion hint */
    const char *ua;               /* the User-Agent string, no "Mobile" token */
} rb_device;

/* --- the catalogue (rb_devices.c, generated) --- */

/* A picker that lays the catalogue out in a fixed buffer sizes it with this.
 * Larger than the catalogue by a comfortable margin, so adding machines to
 * the generator cannot silently truncate a list. */
#define RB_DEVICE_CHOICES_MAX 512

int                 rb_device_count(void);
const rb_device    *rb_device_at(int index);

/* The device with this id, or NULL. NULL and "" are both "no device", so a
 * profile that has never been assigned one needs no special case. */
const rb_device    *rb_device_by_id(const char *id);

/* --- behaviour (rb_device.c) --- */

/* A device not named in taken_ids[0..taken_n). One shared device beats no
 * assignment, so an exhausted pool falls back to the whole catalogue.
 * Returns NULL only if the catalogue itself is empty. */
const rb_device    *rb_device_random(const char *const *taken_ids, int taken_n);

/* The User-Agent the profile behind this device id should send, malloc'd -
 * or NULL when there is no such device and the profile's own UA settings
 * should decide instead. Frees nothing; the caller frees. */
char               *rb_device_ua_for(const char *device_id);

/* A display name for an os field: "windows" -> "Windows 11", "macos" ->
 * "macOS", "linux" -> "Linux". Anything else is returned unchanged, so a
 * caller never has to guard against NULL. */
const char         *rb_device_os_name(const char *os);

/* The document-start script for a device, malloc'd. Mirrors Android's
 * DeviceShim.scriptFor(). Returns NULL on allocation failure. */
char               *rb_device_shim_js(const rb_device *device);

#ifdef __cplusplus
}
#endif

#endif /* RB_DEVICES_H */
