/*
 * rb_devices.h - desktop device catalogue for Room Browser core.
 *
 * The counterpart of the Android edition's Devices.kt: a profile presents
 * itself as a real machine rather than as a bare User-Agent string. The
 * Android catalogue is 1,021 handsets drawn from Google's public list; there
 * is no equivalent list for desktops and far fewer models matter, so this
 * one is curated - real, shipping machines with the OS each one actually
 * runs, the GPU it actually ships, and a Chrome release from its year.
 *
 * The split between the two implementation files is deliberate:
 *
 *   rb_devices.c  the catalogue. GENERATED by scripts/gen-devices.py; do
 *                 not edit by hand. The table itself, plus the three
 *                 lookups that are pure data access.
 *   rb_device.c   behaviour: choosing a device, resolving a profile's
 *                 User-Agent from it, and building the document-start
 *                 script. Hand-written, because it is logic, not data.
 *
 * What a device decides is documented in SECURITY.md, and it is the same
 * bargain the Android edition makes: the non-geometric surface a machine
 * determines (UA, client hints, platform, memory, cores, WebGL strings) is
 * presented. Screen geometry is not, unless the profile asks for it through
 * the Screen size row: the page really is laid out on this display, so the
 * default is to report it honestly, and a profile that claims a size states
 * the claim where the cost of it is visible. Real capabilities - camera,
 * microphones, codecs, battery - are never touched by either edition.
 */

#ifndef RB_DEVICES_H
#define RB_DEVICES_H

#include "rb_settings.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *id;               /* stable id, e.g. "dell-xps-15-9530-windows" */
    const char *brand;            /* "Dell" */
    const char *model;            /* "XPS 15 9530" */
    int         year;             /* release year, 2022-2025 */
    const char *os;               /* "windows" | "macos" | "linux" */
    const char *form;             /* "laptop" | "desktop" */
    const char *arch;             /* "x86" | "arm" - userAgentData architecture */
    const char *chrome;           /* full Chrome version, e.g. "131.0.6778.135" */
    const char *gpu_vendor;       /* WebGL UNMASKED_VENDOR_WEBGL */
    const char *gpu_renderer;     /* WebGL UNMASKED_RENDERER_WEBGL */
    int         cores;            /* hardwareConcurrency */
    int         memory;           /* navigator.deviceMemory - never above 8,
                                     which is where Chromium caps it, so a
                                     64 GB workstation honestly reports 8 */
    const char *platform;         /* navigator.platform: Win32 / MacIntel /
                                     Linux x86_64 */
    const char *ua_platform;      /* userAgentData.platform: Windows / macOS /
                                     Linux */
    const char *platform_version; /* userAgentData platformVersion hint */
    const char *ua;               /* the User-Agent string, no "Mobile" token */
} rb_device;

/* --- the catalogue (rb_devices.c, generated) --- */

/* There is deliberately no maximum here.  A picker sizes itself from
 * rb_device_count() and allocates, because the catalogue is generated and
 * grows: a constant a picker sized a buffer with would be a silent cap on
 * which machines a profile may be given, and the catalogue has outgrown the
 * one this header used to carry. */

int                 rb_device_count(void);
const rb_device    *rb_device_at(int index);

/* The device with this id, or NULL. NULL and "" are both "no device", so a
 * profile that has never been assigned one needs no special case. */
const rb_device    *rb_device_by_id(const char *id);

/* --- behaviour (rb_device.c) --- */

/* A device not named in taken_ids[0..taken_n). One shared device beats no
 * assignment, so an exhausted pool falls back to the whole catalogue.
 * Returns NULL only if the catalogue itself is empty. */
const rb_device    *rb_device_random(const char *const *taken_ids, int taken_n);

/* The User-Agent the profile behind this device id should send, malloc'd -
 * or NULL when there is no such device and the profile's own UA settings
 * should decide instead. Frees nothing; the caller frees. */
char               *rb_device_ua_for(const char *device_id);

/* A display name for an os field: "windows" -> "Windows 11", "macos" ->
 * "macOS", "linux" -> "Linux". Anything else is returned unchanged, so a
 * caller never has to guard against NULL. */
const char         *rb_device_os_name(const char *os);

/* The document-start script for a device, malloc'd. Mirrors Android's
 * DeviceShim.scriptFor(). Returns NULL on allocation failure. */
char               *rb_device_shim_js(const rb_device *device);

/* The document-start script for a claimed screen size, malloc'd, or NULL when
 * there is nothing to claim. Mirrors the screen half of Android's
 * DeviceShim.scriptFor(): it replaces screen.width/height/availWidth/
 * availHeight and derives screen.orientation from the shape claimed, so a
 * claim of a landscape screen cannot also answer "portrait-primary".
 *
 * It deliberately does NOT touch innerWidth, innerHeight or devicePixelRatio.
 * Those are the page's real size on this display and the ratio the compositor
 * renders at; moving them re-lays the page out at a size the screen does not
 * have. The consequence is real and is stated in preferences and SECURITY.md:
 * a claimed screen that differs from the display's is a disagreement with the
 * viewport, and a script can find it. */
char               *rb_screen_shim_js(int width_px, int height_px);

/* The whole document-start script for a profile: the device half when `device`
 * is not NULL, the screen half when the store claims a size, and NULL when
 * neither applies — which is the default state and the one every policy
 * statement in SECURITY.md is about.
 *
 * The two halves are independent so a profile on a UA preset can still state a
 * screen size, and a profile presenting a machine need not claim one. */
char               *rb_shim_js(const rb_device *device, const rb_settings *s);

#ifdef __cplusplus
}
#endif

#endif /* RB_DEVICES_H */
